//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringOccurrencesService
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IStringOccurrencesService")]
    public interface IStringOccurrencesService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStringOccurrencesService/CountOccurrences", ReplyAction = "http://tempuri.org/IStringOccurrencesService/CountOccurrencesResponse")]
        long CountOccurrences(string input, string pattern);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStringOccurrencesService/CountOccurrences", ReplyAction = "http://tempuri.org/IStringOccurrencesService/CountOccurrencesResponse")]
        System.Threading.Tasks.Task<long> CountOccurrencesAsync(string input, string pattern);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringOccurrencesServiceChannel : IStringOccurrencesService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringOccurrencesServiceClient : System.ServiceModel.ClientBase<IStringOccurrencesService>, IStringOccurrencesService
    {

        public StringOccurrencesServiceClient()
        {
        }

        public StringOccurrencesServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public StringOccurrencesServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public StringOccurrencesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public StringOccurrencesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public long CountOccurrences(string input, string pattern)
        {
            return base.Channel.CountOccurrences(input, pattern);
        }

        public System.Threading.Tasks.Task<long> CountOccurrencesAsync(string input, string pattern)
        {
            return base.Channel.CountOccurrencesAsync(input, pattern);
        }
    }
}